import proofs.DegradationControl.Reaction

namespace DegradationControl

def reactionPart [DecidableEq ι] : List (UnaryReaction ι) → Matrix ι ι ℝ
  | [] => 0
  | r :: rs => r.matrix + reactionPart rs

def networkMatrix [DecidableEq ι]
    (rs : List (UnaryReaction ι)) (d : ι → ℝ) : Matrix ι ι ℝ :=
  reactionPart rs + degradationMatrix d

def NonnegativeReaction (r : UnaryReaction ι) : Prop :=
  0 ≤ r.rate ∧ ∀ i, 0 ≤ r.products i

theorem reactionPart_offDiag_nonneg [DecidableEq ι]
    (rs : List (UnaryReaction ι))
    (hrs : ∀ r ∈ rs, NonnegativeReaction r)
    {i j : ι} (hij : i ≠ j) :
    0 ≤ reactionPart rs i j := by
  induction rs with
  | nil => simp [reactionPart]
  | cons r rs ih =>
      have hr : NonnegativeReaction r := hrs r (by simp)
      have hrs' : ∀ q ∈ rs, NonnegativeReaction q := by
        intro q hq
        exact hrs q (by simp [hq])
      simpa [reactionPart] using
        add_nonneg (r.matrix_offDiag_nonneg hr.1 hr.2 hij) (ih hrs')

theorem networkMatrix_offDiag_nonneg [DecidableEq ι]
    (rs : List (UnaryReaction ι)) (d : ι → ℝ)
    (hrs : ∀ r ∈ rs, NonnegativeReaction r)
    {i j : ι} (hij : i ≠ j) :
    0 ≤ networkMatrix rs d i j := by
  simp [networkMatrix, degradationMatrix, hij,
    reactionPart_offDiag_nonneg rs hrs hij]

/-- A nonnegative adjacency matrix carrying exactly the positive off-diagonal
graph of the source-derived reaction matrix.  The unit diagonal only supplies
the positive self-loop convention used by Mathlib's `Matrix.IsIrreducible`; it
does not change reachability between distinct species. -/
noncomputable def sourceAdjacency [DecidableEq ι]
    (rs : List (UnaryReaction ι)) : Matrix ι ι ℝ :=
  fun i j => if i = j then 1 else max (reactionPart rs i j) 0

theorem sourceAdjacency_nonneg [DecidableEq ι]
    (rs : List (UnaryReaction ι)) (i j : ι) :
    0 ≤ sourceAdjacency rs i j := by
  by_cases hij : i = j
  · simp [sourceAdjacency, hij]
  · simp [sourceAdjacency, hij]

theorem sourceAdjacency_offDiag_eq [DecidableEq ι]
    (rs : List (UnaryReaction ι))
    (hrs : ∀ r ∈ rs, NonnegativeReaction r)
    {i j : ι} (hij : i ≠ j) :
    sourceAdjacency rs i j = reactionPart rs i j := by
  simp [sourceAdjacency, hij, reactionPart_offDiag_nonneg rs hrs hij]

/-- Exact source-side irreducibility assumption: the positive off-diagonal
graph generated by the diluted reactions is strongly connected. -/
def SourceIrreducible [DecidableEq ι]
    (rs : List (UnaryReaction ι)) : Prop :=
  Matrix.IsIrreducible (sourceAdjacency rs)

end DegradationControl
